subsection \<open> Simulation Harness\<close>
text \<open>This file is copied from @{verbatim "ITree_Simulation.thy"}. The @{verbatim Simulate} 
Haskell module are updated specifically for security protocols. 
\<close>

theory Sec_Animation
  imports Interaction_Trees.ITree_Extraction Sec_Messages
  keywords "animate_sec" :: "thy_defn" and "animate_sec_sound" :: "thy_defn"
begin

generate_file \<open>code/simulate/Simulate.hs\<close> = \<open>
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE TemplateHaskell #-}

module Simulate (simulate, ppAgent, ppMsg, ppSig, ppK, ppG, ppNmk, ppNonce, ppSet, ppList, ppTrace, ppTraceApp, format_events, 
  format_reach, simulate_cnt, eventList, eventTreeList, formatEvents, TEvent(..), TEventPos(..), EventTree(..), formatTEvent, formatTEvents, 
  explore_tree_cnt, getChannelList, getChannelList4Property 
  ) where
import Interaction_Trees;
import Prelude;
import Text.Read;
import Text.Show.Pretty;
import Data.Text as T (Text, pack)
-- import Data.Text.Encoding  as T
-- import Data.Text.IO        as T
-- import Partial_Fun;
import System.IO;
import Sec_Messages;
import qualified Data.List (dropWhile, dropWhileEnd, intersect, head, tail, elemIndex, uncons);
import Control.Monad (forM_, when);
import Data.Monoid (mempty, mappend);
import System.Exit (exitWith, ExitCode( ExitSuccess ));
-- import System.Random
import System.Random.Stateful;
import Data.Char (isSpace); 
import Arith (Nat(..))
import Set
import FSNat
import qualified Type_Length;
import GHC.Generics (Generic)

splitWhen :: (Char -> Bool) -> String -> [String]
splitWhen p s =  case Data.List.dropWhile p s of
   "" -> []
   s' -> w : splitWhen p s''
         where (w, s'') = Prelude.break p s'

splitOn c = splitWhen (== c)

deleteWhen             :: (a -> Bool) -> [a] -> [a]
deleteWhen _  []       = []
deleteWhen p (y:ys)    = if p y then ys else y : deleteWhen p ys

deleteBy                :: (a -> a -> Bool) -> a -> [a] -> [a]
deleteBy _  _ []        = []
deleteBy eq x (y:ys)    = if x `eq` y then ys else y : deleteBy eq x ys

-- It is not ideal to use this way [show event (prelude.show Chan)=> parse textual event (use read) => pattern match Chan] to pretty print channels
-- But I haven't figured out a way to customise show for Chan without removing 'Prelude.Show' in Chan's definition because it is automatically generated by Isabelle/HOL
--    deriving (Prelude.Read, Prelude.Show);
data ForPrint = FP String;

-- instance Show a => Show (ForPrint a) where 
--   show (FP x) = case (readMaybe x) of
--     Just (Env_C a)   -> "Env"
--     _           -> "Others"

printFP :: ForPrint -> String;
printFP (FP x) = case (read x) of 
  (Env_C (a, b)) -> "Env [" ++ ppAgent a ++ "] " ++ ppAgent b;
  (Send_C (a, (b, (c, d)))) -> "Send [" ++ ppAgent a ++ " -- " ++ ppAgent b ++ " --> " ++ ppAgent c ++ "] " ++ ppMsg d;
  (Recv_C (a, (b, (c, d)))) -> "Recv [" ++ ppAgent a ++ " -- " ++ ppAgent b ++ " --> " ++ ppAgent c ++ "] " ++ ppMsg d;
  (Leak_C d) -> "Leak " ++ ppMsg d ;
  (Sig_C d) -> "Sig " ++ ppSig d ;
  (Terminate_C _) -> "Terminate";
  (Cjam_C m) -> "Error: Jam events are internal and should be properly hidden: \n\t" ++ ppMsg m;
  (Cdejam_C m) -> "Error: Dejam events are internal and should be properly hidden: \n\t" ++ ppMsg m;

ppMsg :: Dmsg a b c d e f g -> String
ppMsg (MAg a) = ppAgent a; 
ppMsg (MNon n) = ppNonce n;
ppMsg (MK k) = ppK k;
ppMsg (MPair m1 m2) = "<" ++ ppMsg m1 ++ ", " ++ ppMsg m2 ++ ">";
ppMsg (MAEnc m k) = ['{'] ++ ppMsg m ++ "}^a" ++ "_" ++ ppMsg k;
ppMsg (MSig m k) = ['{'] ++ ppMsg m ++ "}^d" ++ "_" ++ ppMsg k;
ppMsg (MSEnc m k) = ['{'] ++ ppMsg m ++ "}^s" ++ "_" ++ ppMsg k;
ppMsg (MExpg g) = ppG (MExpg g);
ppMsg (MModExp m e) = ppMsg m ++ ['^'] ++ ppMsg e;
ppMsg (MBitm bm) = ppMBitm (bm);
ppMsg (MWat m bm) = ['{'] ++ ppMsg m ++ "}^w" ++ "_" ++ ppMsg bm;
ppMsg (MJam m bm) = ['{'] ++ ppMsg m ++ "}^j" ++ "_" ++ ppMsg bm;

ppAgent (Agent (Nmk (Nat x))) = "A" ++ ppShow x;
ppAgent (Intruder) = "I";
ppAgent (Server) = "S";

ppNmk (Nmk (Nat x))  = ppShow x;

ppNonce n = "N" ++ ppNmk n;

ppK (Kp x) = "PK" ++ ppNmk x;
ppK (Ks x) = "SK" ++ ppNmk x;

ppG (MExpg g) = "g" ++ ppNmk g;

ppMBitm (Null) = "BMNull";
ppMBitm (Bm bm bl) = "BM"  ++ ppNmk bm ++ ":" ++ ppNmk bl;

ppSet (Set a) = (Prelude.foldl (\x y -> x ++ ppAgent y) "" a)
ppSet _ = ""

ppList a = (Prelude.foldl (\x y -> x ++ y) "" a)

ppSig :: Dsig a b -> String
ppSig (ClaimSecret a n d) = "CliamSecret " ++ "(" ++ ppAgent a ++ ") (" ++ ppNonce n ++ ") (" ++ ppSet d ++ ")";
ppSig (StartProt s d ns nd) = "StartProt " ++ "(" ++ ppAgent s ++ ") (" ++ ppAgent d ++ ") (" ++ ppNonce ns ++ ") (" ++ ppNonce nd ++ ")";
ppSig (EndProt s d ns nd) = "EndProt " ++ "(" ++ ppAgent s ++ ") (" ++ ppAgent d ++ ") (" ++ ppNonce ns ++ ") (" ++ ppNonce nd ++ ")";

data AutoCmd = Auto Int 
  | Rand Int 
  | AReach Int -- Chan -- check reachability of Event
  | RReach Int -- Chan -- check reachability of Event
  | Quit 
  | Manual 
  | Deadlock 
  | Feasible 
  deriving (Prelude.Read, Prelude.Show);

-- These library functions help us to trim the "_C" strings from pretty printed events

isPrefixOf              :: (Eq a) => [a] -> [a] -> Bool;
isPrefixOf [] _         =  True;
isPrefixOf _  []        =  False;
isPrefixOf (x:xs) (y:ys)=  x == y && Simulate.isPrefixOf xs ys;

removeSubstr :: String -> String -> String;
removeSubstr w "" = "";
removeSubstr w s@(c:cs) = (if w `Simulate.isPrefixOf` s then Prelude.drop (Prelude.length w) s else c : removeSubstr w cs);

showTrace :: (Prelude.Show e) => [e] -> String
showTrace [] = "" 
showTrace (t:ts) = (printFP (FP (Prelude.show t))) ++ ", " ++ showTrace ts;

ppTrace e = "[" ++ showTrace e ++ "]"
ppTraceApp e estr = "[" ++ showTrace e ++ estr ++ "]"

containEvents :: (Prelude.Show e) => [e] -> [String] -> Bool
containEvents [] _ = False
containEvents _ [] = False
containEvents ts evs = Prelude.any (\e -> Prelude.elem (printFP (FP (Prelude.show e))) evs) ts

-- %er1;er2;...%
format_events :: String -> [String]
format_events ins = let
    r1 = deleteBy (==) '%' ins;
    r2 = deleteBy (==) '%' r1;
    rl = Simulate.splitOn ';' r2;
    rl1 = map (Data.List.dropWhile (isSpace)) rl;
    rl2 = map (Data.List.dropWhileEnd (isSpace)) rl1
  in rl2 

-- %er1;er2;...% # %em1;em2;...%
-- a list of events for reachability check and a list events for monitor only (so our search won't stop when encountering a monitor event)
format_reach :: String -> ([String], [String])
format_reach ins = 
  let rm = splitOn '#' ins
  in case Data.List.uncons rm of
    Nothing -> ([], []) 
    Just (re, tl) -> case Data.List.uncons tl of
      Nothing -> (format_events re, []) 
      Just (me, tl) -> (format_events re, format_events me)

{- simulate_cnt n P mod steps re me tr
  n: the maximum number of steps that internal events should be executed
  P: the process for animation
  mod: current automation mode
  steps: current no. of steps in automation 
  re: events for reachability check
  me: events for monitor 
  tr: the current trace 
-}
simulate_cnt :: (Eq e, Prelude.Show e, Prelude.Read e, Prelude.Show s) => Prelude.Int -> Itree e s -> AutoCmd -> Prelude.Int -> [String] -> [String] -> [e] -> Prelude.IO ();
simulate_cnt n (Ret x) mod steps re me tr = case mod of
  (AReach _) -> Prelude.putStr ""
  (RReach _) -> Prelude.putStr ""
  _ -> do {
    Prelude.putStrLn ("Successfully Terminated: " ++ Prelude.show x);
    Prelude.putStrLn ("Trace: " ++ (ppTrace tr)) 
  }
simulate_cnt n (Sil p) mod steps re me tr = 
  do { --if (n == 0) then Prelude.putStrLn "Internal Activity..." else return ();
       if (n >= 2000) then do { 
         Prelude.putStr "Many steps (> 2000); Continue? [Y/N]"; 
         q <- Prelude.getLine; 
         if (q == "Y") then simulate_cnt 0 p mod steps re me tr else Prelude.putStrLn "Ended early.";
       }
       else simulate_cnt (n + 1) p mod steps re me tr 
 }

simulate_cnt n (Vis (Pfun_of_alist [])) mod steps re me tr = case mod of
  (AReach _) -> Prelude.putStr "."
  (RReach _) -> Prelude.putStr "."
  _ -> do {
    Prelude.putStrLn "*** Deadlocked ***";
    Prelude.putStrLn ("Trace: " ++ (ppTrace tr))
  }

simulate_cnt n t@(Vis (Pfun_of_alist m)) mod steps re me tr = 
  do { 
      let 
        -- All available visible events, as string
        events = (map (\m -> printFP (FP (Prelude.show (fst m)))) m);
      in 
        do {
          case mod of
            (Auto x) -> if steps >= x then 
            -- switch to manual after specified steps
                do {
                  -- simulate_cnt n t Manual 0 tr
                  -- Prelude.putStrLn ("Auto [" ++ (show x) ++ "] Trace: " ++ (ppTrace tr)) 
                  -- return ()
                  Prelude.putStr ("-")
                } 
              else 
                do {
                  forM_ m $ \s -> simulate_cnt n (snd s) mod (steps+1) re me (tr ++ [fst s]) ;
                  when (steps == 0) (  Prelude.putStrLn ("*** Auto [" ++ (show x) ++ "] Finished ***") )
                  -- if (steps == 0) then 
                  --   do { Prelude.putStrLn ("*** Auto [" ++ (show x) ++ "] Finished ***") }
                  -- else
                  --   do { }
                }
            (Rand x) -> if steps >= x then 
            -- switch to manual after specified steps
                do {
                  -- simulate_cnt n t Manual 0 tr
                  -- Prelude.putStrLn ("Rand [" ++ (show x) ++ "] Trace: " ++ (ppTrace tr)) 
                  -- return ()
                  Prelude.putStr ("-")
                } 
              else 
                do {
                  -- if there is only one event, we don't need to choose
                  if (Prelude.length m == 1) 
                  then do { 
                    -- Prelude.putStrLn ("Random: only 1" ++ "> " ++  (Prelude.show (fst (m !! (0))))) ; 
                    simulate_cnt 0 (snd (m !! (0))) mod (steps + 1) re me (tr ++ [fst (m !! (0))]) 
                    }
                  else
                    do {
                      rn <- applyAtomicGen (uniformR (1 :: Int, Prelude.length m)) globalStdGen;
                      -- let (rn, newg) = uniformR (1 :: Int, Prelude.length m)
                      -- in 
                      do { 
                        -- Prelude.putStrLn ("Random chosen: " ++ show rn ++ "> " ++ (Prelude.show (fst (m !! (rn-1))))) ; 
                        simulate_cnt 0 (snd (m !! (rn-1))) mod (steps + 1) re me (tr ++ [fst (m !! (rn-1))])
                      }
                    }
                  ;
                  when (steps == 0) (  Prelude.putStrLn ("*** Random [" ++ (show x) ++ "] Finished ***") )
                }
            (AReach x) -> if steps >= x then 
                do {
                  -- Prelude.putStrLn ("Auto Reachability [" ++ (show x) ++ "] Trace: " ++ (ppTrace tr)) 
                  -- return ()
                  Prelude.putStr ("-")
                } 
              else 
                do {
                  -- these are events reached now
                  let reached = ppList (Data.List.intersect events re);
                      monitored = Data.List.intersect events me;
                    in if reached /= [] then do {
                      if containEvents tr me then do{
                        Prelude.putStrLn ("*** These events [" ++ reached ++ "] are reached! ***" ++ "\nTrace: " ++ (ppTraceApp tr reached));
                        Prelude.putStrLn ("");
                      }
                      else do {
                        Prelude.putStrLn ("*** These events [" ++ reached ++ "] are reached but no monitored events " ++ (show me) ++ "in the trace! ***" ++ "\nTrace: " ++ (ppTraceApp tr reached));
                        -- hPutStr stderr ("*** These events [" ++ reached ++ "] are reached but no monitored events " ++ (show me) ++ "in the trace! ***" ++ "\nTrace: " ++ (ppTraceApp tr reached) ++ "\n");
                        Prelude.putStrLn ("");
                      }
                    }
                    else do {
                      if monitored /= [] then 
                        Prelude.putStrLn ("*** These events " ++  show monitored ++ " are monitored! ***");
                      else 
                        Prelude.putStr ("");
                      forM_ m $ \s -> simulate_cnt n (snd s) mod (steps+1) re me (tr ++ [fst s]) ;
                      when (steps == 0) (  Prelude.putStrLn ("*** Auto Reachability [" ++ (show x) ++ "] Finished ***") )
                    }
                }
            (RReach x) -> if steps >= x then 
            -- switch to manual after specified steps
                do {
                  -- Prelude.putStrLn ("Random Reachability [" ++ (show x) ++ "] Trace: " ++ (ppTrace tr)) 
                  -- return ()
                  Prelude.putStr ("-")
                } 
              else 
                do {
                  -- these are events reached now
                  let reached = ppList (Data.List.intersect events re);
                      monitored = Data.List.intersect events me;
                    in if reached /= [] then do {
                      if containEvents tr me then do {
                        Prelude.putStrLn ("*** These events [" ++ reached ++ "] are reached! ***" ++ "\nTrace: " ++ (ppTraceApp tr reached));
                        Prelude.putStrLn ("");
                      }
                      else do {
                        Prelude.putStrLn ("*** These events [" ++ reached ++ "] are reached but no monitored events " ++ (show me) ++ "in the trace! ***" ++ "\nTrace: " ++ (ppTraceApp tr reached));
                        -- hPutStr stderr ("*** These events [" ++ reached ++ "] are reached but no monitored events " ++ (show me) ++ "in the trace! ***" ++ "\nTrace: " ++ (ppTraceApp tr reached) ++ "\n");
                        Prelude.putStrLn ("");
                      }
                    }
                    else do {
                       if monitored /= [] then 
                        Prelude.putStrLn ("*** These events " ++  show monitored ++ " are monitored! ***");
                      else 
                        Prelude.putStr ("");

                      -- if there is only one event, we don't need to choose
                      if (Prelude.length m == 1) 
                      then do { 
                        -- Prelude.putStrLn ("Reachability Random: only 1" ++ "> " ++  (Prelude.show (fst (m !! (0))))) ; 
                        simulate_cnt 0 (snd (m !! (0))) mod (steps + 1) re me (tr ++ [fst (m !! (0))]) 
                        }
                      else
                        do {
                          rn <- applyAtomicGen (uniformR (1 :: Int, Prelude.length m)) globalStdGen;
                          -- let (rn, newg) = uniformR (1 :: Int, Prelude.length m)
                          -- in 
                          do { 
                            -- Prelude.putStrLn ("Random chosen: " ++ show rn ++ "> " ++ (Prelude.show (fst (m !! (rn-1))))) ; 
                            simulate_cnt 0 (snd (m !! (rn-1))) mod (steps + 1) re me (tr ++ [fst (m !! (rn-1))])
                          }
                        }
                      ;
                      when (steps == 0) (  Prelude.putStrLn ("*** Random Reachability [" ++ (show x) ++ "] Finished ***") )
                    }
                }
            (Feasible) -> case Data.List.uncons re of
              Nothing -> do {Prelude.putStrLn ("*** The specified trace is feasible ****")}
              Just (hd, tl) -> -- in if cur_event_to_check `elem` events then
                  case Data.List.elemIndex hd events of
                    Just rn -> do {
                      simulate_cnt 0 (snd (m !! (rn))) mod (steps + 1) tl me (tr ++ [fst (m !! (rn))])
                    }
                    Nothing -> do {Prelude.putStrLn ("*** Event [" ++ hd ++ "] is not feasible in current state \nwhere feasible events include \t" ++ show events)}
                
            (Quit) -> Prelude.putStrLn "Simulation terminated";
            (Manual) -> do { 
              -- Manual
                 Prelude.putStrLn ("Events:\n" ++ Prelude.concat (map (\(n, e) -> " (" ++ ppShow n ++ ") " ++ removeSubstr "_C" e ++ ";\n") (zip [1..] events)));
                 -- Prelude.putStrLn ("Events:\n" ++ Prelude.concat (map (\(n, e) -> " (" ++ ppShow n ++ ") " ++ removeSubstr "_C" e ++ ";\n") (zip [1..] (map (\m -> (Prelude.show (fst m))) m))));
                 Prelude.putStr ("[Choose: 1-" ++ Prelude.show (Prelude.length m) ++ "]: ");
                 e <- Prelude.getLine;
                 
                 do {
                  -- try to parse AutoCmd 
                  case (Prelude.reads e)::[(AutoCmd, String)] of
                    []       -> do { 
                      -- Prelude.putStrLn "Not AutoCmd, use Manual";
                      -- Other commands
                      if (e == "q" || e == "Q") then
                        do {
                            Prelude.putStrLn ("*** Simulation terminated ***"); 
                            Prelude.putStrLn ("Trace: " ++ (ppTrace tr));
                            System.Exit.exitWith System.Exit.ExitSuccess
                        }
                      else if (e == "h" || e == "H") then
                        do {
                            Prelude.putStrLn ("*** Usage ***"); 
                            Prelude.putStrLn ("Auto n : Exhaustive search of traces up to n events or length;");
                            Prelude.putStrLn ("Rand n : Random search of a trace up to n events or length;");
                            Prelude.putStrLn ("AReach n %er1;er2;...%[#%em1;em2;...%] : Exhaustive search of traces up to n events or length, or if the specified events (er) are reached with optional events for monitor (em);");
                            Prelude.putStrLn ("RReach n %er1;er2;...%[#%em1;em2;...%] : Random search of a trace up to n events or length, or if the specified events (er) are reached with optional events for monitor (em);");
                            Prelude.putStrLn ("Feasible %event1;event2;...% : Check whether the specified sequence of events is a feasible trace from current state.\n");
                            -- System.Exit.exitWith System.Exit.ExitSuccess
                            simulate_cnt n t mod steps re me tr 
                        }
                      else
                        case (Prelude.reads e) of
                          []       -> if (Prelude.length m == 1)
                                        then do { Prelude.putStrLn ( (Prelude.show (fst (m !! 0)))) ; simulate_cnt 0 (snd (m !! (0))) mod steps re me (tr ++ [fst (m !! 0)]) }
                                        else do { Prelude.putStrLn "No parse"; simulate_cnt n t mod steps re me tr }
                          [(v, _)] -> if (v > Prelude.length m)
                                        then do { Prelude.putStrLn "Rejected"; simulate_cnt n t mod steps re me tr }
                                        else do { Prelude.putStrLn ( (Prelude.show (fst (m !! (v-1))))) ; simulate_cnt 0 (snd (m !! (v - 1))) mod steps re me (tr ++ [fst (m !! (v-1))]) }

                      }
                    -- parsed AutoCmd where r is the rest string after a, parsed AutoCmd 
                    [(a, r)] -> do {
                      Prelude.putStrLn (show a ++ ", " ++ r);
                      case a of 
                        (Auto x) ->  do { -- Prelude.putStrLn ("Auto " ++ show x); 
                            simulate_cnt n t a 0 [] [] tr }
                        (Rand x) ->  do { -- Prelude.putStrLn ("Random " ++ show x); 
                            simulate_cnt n t a 0 [] [] tr }
                        (AReach x) ->  do {
                          let (res,mes) = format_reach r
                          in do {
                            Prelude.putStrLn ("Reachability by Auto: " ++ show x ++ "\n  Events for reachability check: " ++ show res ++ "\n  Events for monitor: " ++ show mes); 
                            simulate_cnt n t a 0 res mes tr 
                          }
                        }
                        (RReach x) ->  do {
                          let (res,mes) = format_reach r
                          in do {
                            Prelude.putStrLn ("Reachability by Random: " ++ show x ++ "\n  Events for reachability check: " ++ show res ++ "\n  Events for monitor: " ++ show mes); 
                            simulate_cnt n t a 0 res mes tr 
                          }
                        }
                        (Feasible) ->  do {
                          let fe = format_events r
                          in do {
                            Prelude.putStrLn ("Feasibility check the sequence of events: " ++ show fe); simulate_cnt n t a 0 fe me tr 
                          }
                        }
                        (Quit) -> do {
                            Prelude.putStrLn ("*** Simulation terminated ***"); 
                            Prelude.putStrLn ("Trace: " ++ (ppTrace tr));
                            System.Exit.exitWith System.Exit.ExitSuccess
                        }
                        _ -> do {Prelude.putStrLn ("Unknown " ++ show a)}
                      }
                  }
              }
         }
         
--       if (e == "q" || e == "Q") then
--         Prelude.putStrLn "Simulation terminated"
--       else
--        case (Prelude.reads e) of
--          []       -> if (Prelude.length m == 1)
--                        then do { Prelude.putStrLn ( (Prelude.show (fst (m !! 0)))) ; simulate_cnt 0 (snd (m !! (0)))}
--                        else do { Prelude.putStrLn "No parse"; simulate_cnt n t }
--          [(v, _)] -> if (v > Prelude.length m)
--                        then do { Prelude.putStrLn "Rejected"; simulate_cnt n t }
--                        else do { Prelude.putStrLn ( (Prelude.show (fst (m !! (v-1))))) ; simulate_cnt 0 (snd (m !! (v - 1)))}
     };
simulate_cnt n t@(Vis (Pfun_of_map f)) mod steps re me tr = 
  do { Prelude.putStr ("Enter an event:");
       e <- Prelude.getLine;
       if (e == "q" || e == "Q") then
         Prelude.putStrLn "Simulation terminated"
       else
       case (Prelude.reads e) of
         []       -> do { Prelude.putStrLn "No parse"; simulate_cnt n t mod steps re me tr } 
         [(v, _)] -> case f v of
                       Nothing -> do { Prelude.putStrLn "Rejected"; simulate_cnt n t mod steps re me tr }
                       Just t' -> simulate_cnt 0 t' mod steps re me tr 
     };                                                                

simulate :: (Eq e, Prelude.Show e, Prelude.Read e, Prelude.Show s) => Itree e s -> Prelude.IO ();
simulate p = do { hSetBuffering stdout NoBuffering; putStrLn ""; putStrLn "Starting ITree Animation..."; simulate_cnt 0 p (Manual) 0 [] [] []}

eventList :: (Eq e, Prelude.Show e, Prelude.Read e, Prelude.Show s) => Itree e s -> Maybe [e];
eventList (Ret x) = Nothing 
eventList (Sil p) = eventList p 
eventList t@(Vis (Pfun_of_alist [])) = Just [] 
eventList t@(Vis (Pfun_of_alist m)) = Just $ map fst m 
eventList t@(Vis (Pfun_of_map f)) = error "Not supported Pfun_of_map" 

eventTreeList :: (Eq e, Prelude.Show e, Prelude.Read e, Prelude.Show s) => Itree e s -> Maybe [(e, Itree e s)];
eventTreeList (Ret x) = Nothing 
eventTreeList (Sil p) = eventTreeList p 
eventTreeList t@(Vis (Pfun_of_alist [])) = Just [] 
eventTreeList t@(Vis (Pfun_of_alist m)) = Just $ m 
eventTreeList t@(Vis (Pfun_of_map f)) = error "Not supported Pfun_of_map" 

formatEvents :: (Chan a b c d e f g) -> (String, String, String, String, String); 
formatEvents (Env_C (a, b)) = ("Env", "Env", "Env", ppAgent a, ppAgent b); 
formatEvents (Send_C (a, (b, (c, d)))) = ("Send", ppAgent a, ppAgent b, ppAgent c, ppMsg d); 
formatEvents (Recv_C (a, (b, (c, d)))) = ("Recv", ppAgent a, ppAgent b, ppAgent c, ppMsg d); 
formatEvents (Leak_C d) = ("Leak", "Intruder", "Intruder", "Env", ppMsg d); 
formatEvents (Sig_C s) = case s of 
  (ClaimSecret a n d) -> case d of 
    Set.Set [x] -> ("[Sig]ClaimSecret", ppAgent a, ppAgent a, ppAgent x, ppNonce n); 
    _ -> ("[Sig]ClaimSecret", ppAgent a, ppAgent a,"", ppNonce n); 
  (StartProt s d ns nd) -> ("[Sig]StartProt", ppAgent s, ppAgent s, ppAgent d, ppNonce ns ++ "/" ++ ppNonce nd); 
  (EndProt s d ns nd) -> ("[Sig]EndProt", ppAgent s, ppAgent s, ppAgent d, ppNonce ns ++ "/" ++ ppNonce nd); 
formatEvents (Terminate_C _) = ("Terminate", "Sys", "Sys", "Env", "");

animate_manual :: (Eq e, Prelude.Show e, Prelude.Read e, Prelude.Show s) => Itree e s -> e -> (String, Maybe (Itree e s)); 
animate_manual (Ret x) e = ("Terminated. ",  Nothing)
animate_manual (Sil p) e = (animate_manual p e)
animate_manual t@(Vis (Pfun_of_alist [])) e = ("Deadlocked. ", Nothing) 
animate_manual t@(Vis (Pfun_of_alist m)) e = 
  if (e `elem` map fst m) then 
    ("event" ++ (Prelude.show e) ++ " animated. ", Just $ pfun_app (Pfun_of_alist m) e) 
  else 
    ("Not enabled event " ++ (Prelude.show e) ++ ". ", Just t)

-- | Tree Event
-- Root: the root of the tree
-- Deadlocked: deadlocked state
-- Terminated: terminated state
-- Divergence: divergence after some fixed tau steps
-- EChan: Chan event 
data TEvent a b c d e f g = Root | Deadlocked | Terminated | Divergent | EChan (Sec_Messages.Chan a b c d e f g) 
  deriving (Eq, Read, Show, Generic)

-- | Tree Event with its position 
-- TEP: an event with its depth and event numbering in that depth (to uniquely identify the event in the tree) 
data TEventPos a b c d e f g = TEP Int Int (TEvent a b c d e f g)
  deriving (Eq, Read, Show, Generic)

-- | Event tree
data EventTree a b c d e f g = ETNode (TEventPos a b c d e f g) [EventTree a b c d e f g] 
  deriving (Eq, Read, Show, Generic)

-- | Format a tree event to text
formatTEvent :: TEvent a b c d e f g -> Text
formatTEvent e = case e of 
  Root -> T.pack $ "ROOT"
  Deadlocked -> T.pack $ "Deadlocked"
  Terminated -> T.pack $ "Terminated"
  Divergent -> T.pack $ "Divergent"
  EChan e -> let (ch, src, medium, desc, msg) = formatEvents e in 
    (T.pack $ ch) <> (T.pack ":") <> (T.pack $ msg)

-- | Format a list of tree events to text
formatTEvents :: [TEvent a b c d e f g] -> Text
formatTEvents [] = T.pack $ ""
formatTEvents (x:xs) = formatTEvent x <> (T.pack "; ") <> formatTEvents xs

-- | A function to exhaustively explore an ITree for given steps and 
-- steps: the maximum number of steps that external events should be executed 
-- cur_step: the current number of steps that external events have been executed 
-- tau_steps: the maximum number of steps that internal events should be executed 
-- cur_tau_step: the current number of steps that internal events have been executed 
explore_tree_cnt :: (Prelude.Show s) => forall a b c d e f g. Itree (Chan a b c d e f g) s -> Int -> Int -> Int -> Int -> [EventTree a b c d e f g]; 
explore_tree_cnt (Ret x) steps cur_step tau_steps cur_tau_step = [ETNode (TEP cur_step 0 Terminated) []] 
explore_tree_cnt (Sil p) steps cur_step tau_steps cur_tau_step = 
  if cur_tau_step == 0 then [ETNode (TEP cur_step 0 Divergent) []] else (explore_tree_cnt p steps cur_step tau_steps (cur_tau_step - 1))
explore_tree_cnt t@(Vis (Pfun_of_alist [])) steps cur_step tau_steps cur_tau_step = [ETNode (TEP cur_step 0 Deadlocked) []]
explore_tree_cnt t@(Vis (Pfun_of_alist m)) steps cur_step tau_steps cur_tau_step = if cur_step < steps then 
    map (\(i, (e, etree)) -> ETNode (TEP cur_step i (EChan e)) (explore_tree_cnt etree (steps) (cur_step + 1) tau_steps tau_steps)) (zip [(1::Int)..] m) 
  else []
explore_tree_cnt t@(Vis (Pfun_of_map f)) steps cur_step tau_steps cur_tau_step = error "Not supported Pfun_of_map"
explore_tree_cnt t@(Vis (Pfun_entries _ _)) steps cur_step tau_steps cur_tau_step = error "Not supported Pfun_entries"

-- | Get the list of channels 
getChannelList :: [String]
getChannelList = ["Send", "Recv", "Hear", "Fake", "Leak", "[Sig]ClaimSecret", "[Sig]StartProt", "[Sig]EndProt", "Terminate"]

-- | Get the list of channels for property checking 
getChannelList4Property :: [String]
getChannelList4Property = ["Leak", "[Sig]ClaimSecret", "[Sig]StartProt", "[Sig]EndProt", "Terminate", "Deadlocked", "Divergent"]
\<close>

subsection \<open> Sound bounded exploration \<close>

text \<open>
  The terminal animator and the browser interface both search the event space by
  running the hand-written Haskell functions @{verbatim simulate_cnt} and
  @{verbatim explore_tree_cnt}.  Those functions are only trusted, not proved:
  nothing rules out a search that silently misses a branch of the event tree.

  The definitions below replace that trusted search by a search that is defined
  in Isabelle/HOL.  @{text explore} returns, for a bounded number of visible
  events and internal steps, \emph{all} traces of an ITree; it is executable and
  its Haskell rendering is obtained from these definitions by the code
  generator.  @{text btr} is the inductive characterisation of the same traces,
  and the two theorems @{text explore_sound} and @{text explore_complete} state
  that @{text explore} neither invents nor misses a trace:
  \begin{itemize}
    \item @{text explore_sound}: every explored trace is a trace of the ITree,
      witnessed by the operational semantics @{text trace_to};
    \item @{text explore_complete}: every trace of the ITree of bounded length
      is explored, provided the bound on internal steps is large enough.
  \end{itemize}
  The bounds are written with \<open>0\<close>/\<open>Suc\<close> patterns, which is convenient for
  the proofs; arithmetic code equations are installed further below because
  \<^typ>\<open>nat\<close> is translated to Haskell as an opaque integer.
\<close>

fun explore :: "nat \<Rightarrow> nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> 'e list set" where
  "explore 0 mx t P = {[]}"
| "explore (Suc n) mx t (Ret x) = {[]}"
| "explore (Suc n) mx 0 (Sil Q) = {[]}"
| "explore (Suc n) mx (Suc t) (Sil Q) = explore (Suc n) mx t Q"
| "explore (Suc n) mx t (Vis F) =
     {[]} \<union> \<Union> (((\<lambda>e. (#) e ` explore n mx mx (F e)) ` pdom F))"

text \<open> The inductive characterisation of the explored traces: \<open>n\<close> is the
  remaining number of visible events, \<open>mx\<close> the internal-step budget that is
  granted again after each visible event, and \<open>t\<close> the remaining part of that
  budget at the current state. \<close>

inductive btr :: "nat \<Rightarrow> nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> 'e list \<Rightarrow> bool" where
  btr_stop: "btr n mx t P []"
| btr_Sil: "btr (Suc n) mx t P tr \<Longrightarrow> btr (Suc n) mx (Suc t) (Sil P) tr"
| btr_Vis: "e \<in> pdom F \<Longrightarrow> btr n mx mx (F e) tr \<Longrightarrow> btr (Suc n) mx t (Vis F) (e # tr)"

lemma Nil_in_explore [simp]: "[] \<in> explore n mx t P"
  by (induct n mx t P rule: explore.induct) auto

lemma btr_imp_explore: "btr n mx t P tr \<Longrightarrow> tr \<in> explore n mx t P"
  by (induct rule: btr.induct) (auto simp: image_iff)

lemma explore_imp_btr: "tr \<in> explore n mx t P \<Longrightarrow> btr n mx t P tr"
  by (induct n mx t P arbitrary: tr rule: explore.induct) (auto intro: btr.intros)

lemma explore_iff_btr: "tr \<in> explore n mx t P \<longleftrightarrow> btr n mx t P tr"
  by (auto intro: btr_imp_explore explore_imp_btr)

lemma btr_nil [intro]: "btr n mx t P []"
  by (rule btr_stop)

lemma btr_mono: "btr n mx t P tr \<Longrightarrow> mx \<le> mx' \<Longrightarrow> t \<le> t' \<Longrightarrow> btr n mx' t' P tr"
proof (induct arbitrary: mx' t' rule: btr.induct)
  case (btr_stop n mx t P) then show ?case by (auto intro: btr.intros)
next
  case (btr_Sil n mx t P tr) then show ?case
    by (cases t') (auto elim: btr.cases intro: btr.intros)
next
  case (btr_Vis e F n mx t tr) then show ?case by (auto intro: btr.intros)
qed

lemma btr_mono_n: "btr n mx t P tr \<Longrightarrow> n \<le> n' \<Longrightarrow> btr n' mx t P tr"
proof (induct arbitrary: n' rule: btr.induct)
  case (btr_stop n mx t P) then show ?case by (auto intro: btr.intros)
next
  case (btr_Sil n mx t P tr) then show ?case
    by (cases n') (auto elim: btr.cases intro: btr.intros)
next
  case (btr_Vis e F n mx t tr) then show ?case
    by (cases n') (auto elim: btr.cases intro: btr.intros)
qed

lemma btr_sound: "btr n mx t P tr \<Longrightarrow> length tr \<le> n \<and> (\<exists>P'. P \<midarrow>tr\<leadsto> P')"
  by (induct rule: btr.induct) (auto intro: trace_to_Sil trace_to_Vis trace_to_Nil)

text \<open> Every trace reported by the sound exploration is a genuine trace of the
  model, and its length respects the bound. \<close>

theorem explore_sound:
  assumes "tr \<in> explore n mx mx P"
  shows "length tr \<le> n \<and> (\<exists>P'. P \<midarrow>tr\<leadsto> P')"
  using assms by (metis btr_sound explore_iff_btr)

lemma trace_to_btr: "P \<midarrow>tr\<leadsto> P' \<Longrightarrow> \<exists>mx. btr (length tr) mx mx P tr"
proof (induct rule: trace_to.induct)
  case (trace_to_Nil P)
  then show ?case by (intro exI[of _ 0]) (auto intro: btr.intros)
next
  case (trace_to_Sil P tr P')
  then obtain mx where "btr (length tr) mx mx P tr" by blast
  then show ?case
  proof (cases tr)
    case Nil
    then show ?thesis by (intro exI[of _ 1]) (auto intro: btr.intros)
  next
    case (Cons e rest)
    with \<open>btr (length tr) mx mx P tr\<close>
    have "btr (Suc (length rest)) (Suc mx) mx P (e # rest)"
      by (auto intro: btr_mono)
    then show ?thesis
      using Cons by (intro exI[of _ "Suc mx"]) (auto intro: btr.intros)
  qed
next
  case (trace_to_Vis e F tr P')
  then obtain mx where ih: "btr (length tr) mx mx (F e) tr" by blast
  have dom: "e \<in> pdom F" using trace_to_Vis by blast
  show ?case
    by (intro exI[of _ mx]) (metis btr_Vis dom ih length_Cons)
qed

text \<open> Conversely, every genuine trace of the model is explored, provided the
  internal-step budget is chosen large enough.  There is therefore neither a
  missed branch nor a spurious counterexample in the bounded search. \<close>

theorem explore_complete:
  assumes "P \<midarrow>tr\<leadsto> P'"
    and "length tr \<le> n"
  shows "\<exists>mx. tr \<in> explore n mx mx P"
proof -
  from assms(1) obtain mx where bt: "btr (length tr) mx mx P tr" by (meson trace_to_btr)
  with assms(2) have "btr n mx mx P tr" by (auto intro: btr_mono_n)
  then show ?thesis by (auto simp add: explore_iff_btr)
qed

text \<open> Feasibility of a given trace and reachability of a set of events under a
  monitor, both decided by the same explored set. \<close>

definition feasible :: "nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> 'e list \<Rightarrow> bool" where
  "feasible n mx P tr \<longleftrightarrow> tr \<in> explore n mx mx P"

lemma feasible_iff_btr: "feasible n mx P tr \<longleftrightarrow> btr n mx mx P tr"
  by (simp add: feasible_def explore_iff_btr)

lemma feasible_sound:
  "feasible n mx P tr \<Longrightarrow> length tr \<le> n \<and> (\<exists>P'. P \<midarrow>tr\<leadsto> P')"
  by (simp add: feasible_iff_btr btr_sound)

definition reaches :: "nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> 'e list \<Rightarrow> 'e list \<Rightarrow> bool" where
  "reaches n mx P re me \<longleftrightarrow>
     Set.filter (\<lambda>tr. (\<exists>e\<in>set re. e \<in> set tr) \<and> (me = [] \<or> (\<exists>m\<in>set me. m \<in> set tr)))
       (explore n mx mx P) \<noteq> {}"

text \<open> Reachability only ever reports traces that really exist in the model:
  the monitor condition holds along the reported trace. \<close>

lemma reaches_sound:
  assumes "reaches n mx P re me"
  shows "\<exists>tr. tr \<in> explore n mx mx P
    \<and> (\<exists>e\<in>set re. e \<in> set tr) \<and> (me = [] \<or> (\<exists>m\<in>set me. m \<in> set tr))"
  using assms by (auto simp add: reaches_def Set.filter_def)

text \<open> Executable arithmetic code equations.  The pattern equations above are
  removed from the code set because the code generator translates \<^typ>\<open>nat\<close> to
  an opaque integer and cannot match on \<open>0\<close>/\<open>Suc\<close>. \<close>

lemma explore_code_Ret [code]: "explore n mx t (Ret x) = {[]}"
  by (cases n; simp)

lemma explore_code_Sil [code]:
  "explore n mx t (Sil Q) =
     (if n = 0 then {[]} else if t = 0 then {[]} else explore n mx (t - 1) Q)"
  by (cases n; cases t; simp)

lemma explore_code_Vis [code]:
  "explore n mx t (Vis F) =
     (if n = 0 then {[]}
      else {[]} \<union> \<Union> (((\<lambda>e. (#) e ` explore (n - 1) mx mx (F e)) ` pdom F)))"
  by (cases n; simp)

declare explore.simps(1) [code del]
declare explore.simps(2) [code del]
declare explore.simps(3) [code del]
declare explore.simps(4) [code del]
declare explore.simps(5) [code del]

text \<open> Was the bounded exploration cut short by the internal-step budget?
  @{text explore} stops without following a state whose internal budget is
  exhausted; this predicate reports that, so that a bounded verdict can be
  flagged as possibly incomplete and the user asked to raise @{text mx}.
  It mirrors the @{text explore} recursion clause by clause. \<close>

fun budget_hit :: "nat \<Rightarrow> nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> bool" where
  "budget_hit 0 mx t P = False"
| "budget_hit (Suc n) mx t (Ret x) = False"
| "budget_hit (Suc n) mx 0 (Sil Q) = True"
| "budget_hit (Suc n) mx (Suc t) (Sil Q) = budget_hit (Suc n) mx t Q"
| "budget_hit (Suc n) mx t (Vis F) = (\<exists>e\<in>pdom F. budget_hit n mx mx (F e))"

text \<open> Executable arithmetic code equations, mirroring those of
  @{const explore}: the pattern equations are removed from the code set because
  the code generator translates @{typ nat} to an opaque integer. \<close>

lemma budget_hit_code_Ret [code]: "budget_hit n mx t (Ret x) = False"
  by (cases n; simp)

lemma budget_hit_code_Sil [code]:
  "budget_hit n mx t (Sil Q) =
     (if n = 0 then False else if t = 0 then True else budget_hit n mx (t - 1) Q)"
  by (cases n; cases t; simp)

lemma budget_hit_code_Vis [code]:
  "budget_hit n mx t (Vis F) =
     (if n = 0 then False else (\<exists>e\<in>pdom F. budget_hit (n - 1) mx mx (F e)))"
  by (cases n; simp)

declare budget_hit.simps(1) [code del]
declare budget_hit.simps(2) [code del]
declare budget_hit.simps(3) [code del]
declare budget_hit.simps(4) [code del]
declare budget_hit.simps(5) [code del]

subsection \<open> Bounded checking of trace properties \<close>

text \<open>
  @{text explore} is an explorer: it enumerates every trace within the bounds.
  A \emph{check} filters that enumeration by a property of traces, so its result
  is the set of counterexamples and its verdict is the emptiness of that set.
  Soundness and bounded completeness of a check are inherited directly from the
  exploration, so a check can neither invent a counterexample nor miss one
  within the bounds.
\<close>

definition checks :: "nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> ('e list \<Rightarrow> bool) \<Rightarrow> 'e list set" where
  "checks n mx P pred = Set.filter pred (explore n mx mx P)"

definition has_counterexample :: "nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> ('e list \<Rightarrow> bool) \<Rightarrow> bool" where
  "has_counterexample n mx P pred \<longleftrightarrow> checks n mx P pred \<noteq> {}"

lemma checks_iff: "tr \<in> checks n mx P pred \<longleftrightarrow> btr n mx mx P tr \<and> pred tr"
  by (auto simp add: checks_def explore_iff_btr)

text \<open> Every counterexample returned by a check is a genuine trace of the
  model that really has the checked property. \<close>

theorem checks_sound:
  assumes "tr \<in> checks n mx P pred"
  shows "pred tr \<and> length tr \<le> n \<and> (\<exists>P'. P \<midarrow>tr\<leadsto> P')"
  using assms by (auto simp add: checks_def dest: explore_sound)

text \<open> Conversely, every genuine trace of bounded length with the property is
  returned by the check, for a large enough internal-step bound.  A check that
  reports nothing therefore rules the property out within the bounds. \<close>

theorem checks_complete:
  assumes "P \<midarrow>tr\<leadsto> P'"
    and "length tr \<le> n"
    and "pred tr"
  shows "\<exists>mx. tr \<in> checks n mx P pred"
  using assms by (auto simp add: checks_def intro: explore_complete)

text \<open> Checks of the security-relevant events of the framework.  The generic
  correspondence checks look for a reachability event with (or without) a
  monitor event before it, which is how secrecy and authenticity are phrased. \<close>

definition is_leak :: "('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan \<Rightarrow> bool" where
  "is_leak e \<longleftrightarrow> (case e of leak_C _ \<Rightarrow> True | _ \<Rightarrow> False)"

definition is_sig :: "('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan \<Rightarrow> bool" where
  "is_sig e \<longleftrightarrow> (case e of sig_C _ \<Rightarrow> True | _ \<Rightarrow> False)"

definition is_start :: "('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan \<Rightarrow> bool" where
  "is_start e \<longleftrightarrow> (case e of sig_C (StartProt _ _ _ _) \<Rightarrow> True | _ \<Rightarrow> False)"

definition is_end :: "('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan \<Rightarrow> bool" where
  "is_end e \<longleftrightarrow> (case e of sig_C (EndProt _ _ _ _) \<Rightarrow> True | _ \<Rightarrow> False)"

text \<open> The intruder is the only principal that does not run the protocol, so an honest peer is
  every other agent.  Sessions whose counterpart is the intruder are not agreement requirements,
  since the intruder never starts a session and would otherwise make every completion a
  counterexample. \<close>

definition is_honest :: "('a::{len,typerep}) dagent \<Rightarrow> bool" where
  "is_honest a \<longleftrightarrow> (case a of Intruder \<Rightarrow> False | _ \<Rightarrow> True)"

text \<open> The signal a completed run @{text "EndProt s d ns nd"} must have been preceded by: the
  counterpart @{text d} starting the same session with @{text s}, with the same two nonces in the
  same order.  Comparing the participants is what makes this an authenticity check; matching on
  @{text StartProt} alone would be satisfied by the completer's own start signal. \<close>

definition matches_start :: "('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan \<Rightarrow>
    ('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan \<Rightarrow> bool" where
  "matches_start e_end e_start \<longleftrightarrow>
     (case (e_end, e_start) of
        (sig_C (EndProt s d ns nd), sig_C (StartProt s' d' ns' nd')) \<Rightarrow>
          s' = d \<and> d' = s \<and> ns' = ns \<and> nd' = nd
      | _ \<Rightarrow> False)"

text \<open> A completed run of two honest agents, which is what the authenticity check requires a
  matching start signal for. \<close>

definition is_end_honest :: "('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan \<Rightarrow> bool" where
  "is_end_honest e \<longleftrightarrow> (case e of sig_C (EndProt s d _ _) \<Rightarrow> is_honest s \<and> is_honest d | _ \<Rightarrow> False)"

definition is_terminate :: "('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan \<Rightarrow> bool" where
  "is_terminate e \<longleftrightarrow> (case e of terminate_C () \<Rightarrow> True | _ \<Rightarrow> False)"

definition check_leak :: "nat \<Rightarrow> nat \<Rightarrow>
    (('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan, 'st) itree \<Rightarrow> ('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan list set" where
  "check_leak n mx P = checks n mx P (\<lambda>tr. \<exists>e\<in>set tr. is_leak e)"

definition check_leak_msg :: "nat \<Rightarrow> nat \<Rightarrow>
    (('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan, 'st) itree \<Rightarrow> ('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) dmsg \<Rightarrow> ('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan list set" where
  "check_leak_msg n mx P m =
     checks n mx P (\<lambda>tr. \<exists>e\<in>set tr. (case e of leak_C m' \<Rightarrow> m' = m | _ \<Rightarrow> False))"

definition check_sig :: "nat \<Rightarrow> nat \<Rightarrow>
    (('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan, 'st) itree \<Rightarrow> ('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan list set" where
  "check_sig n mx P = checks n mx P (\<lambda>tr. \<exists>e\<in>set tr. is_sig e)"

definition check_terminate :: "nat \<Rightarrow> nat \<Rightarrow>
    (('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan, 'st) itree \<Rightarrow> ('a::{len,typerep}, 'n::{len,typerep}, 'k::{len,typerep}, 's::{len,typerep}, 'g::{len,typerep}, 'bm::{len,typerep}, 'bl::{len,typerep}) chan list set" where
  "check_terminate n mx P = checks n mx P (\<lambda>tr. \<exists>e\<in>set tr. is_terminate e)"

definition check_corr :: "nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> ('e \<Rightarrow> bool) \<Rightarrow> ('e \<Rightarrow> bool) \<Rightarrow> 'e list set" where
  "check_corr n mx P mon re =
     checks n mx P (\<lambda>tr. tr \<noteq> [] \<and> re (last tr) \<and> (\<exists>e\<in>set (butlast tr). mon e))"

definition check_corr_violation :: "nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> ('e \<Rightarrow> bool) \<Rightarrow> ('e \<Rightarrow> bool) \<Rightarrow> 'e list set" where
  "check_corr_violation n mx P mon re =
     checks n mx P (\<lambda>tr. tr \<noteq> [] \<and> re (last tr) \<and> \<not> (\<exists>e\<in>set (butlast tr). mon e))"

text \<open> A correspondence violation whose trigger is related to the last event, so that the two
  participants (and not just the kind of signal) can be compared.  The relation parameter is called
  @{text rel} and not @{text matches}: the name @{text matches} collides with the implicit-structure
  syntax of the imported ITree/UTP context, and Isabelle then rejects it as a bound variable with
  ``Illegal reference to implicit structure''. \<close>

definition check_auth_violation :: "nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> ('e \<Rightarrow> 'e \<Rightarrow> bool) \<Rightarrow> ('e \<Rightarrow> bool) \<Rightarrow> 'e list set" where
  "check_auth_violation n mx P rel re =
     checks n mx P (\<lambda>tr. tr \<noteq> [] \<and> re (last tr) \<and> \<not> (\<exists>e\<in>set (butlast tr). rel (last tr) e))"

definition "check_authenticity n mx P = check_auth_violation n mx P matches_start is_end_honest"

text \<open> @{text check_leak} finds every explored trace that leaks a message,
  @{text check_sig} every trace with a claim/start/end signal, and
  @{text check_authenticity} every trace in which two honest agents complete a run
  @{text "EndProt s d ns nd"} although the counterpart never started that session, that is,
  without a matching @{text "StartProt d s ns nd"} before it.  All of them are
  executable and return their counterexamples. \<close>

lemma check_leak_sound:
  assumes "tr \<in> check_leak n mx P"
  shows "\<exists>e\<in>set tr. is_leak e"
proof -
  from assms have "tr \<in> checks n mx P (\<lambda>tr. \<exists>e\<in>set tr. is_leak e)"
    by (simp add: check_leak_def)
  from checks_sound[OF this] show ?thesis by simp
qed

lemma check_corr_violation_sound:
  assumes "tr \<in> check_corr_violation n mx P mon re"
  shows "tr \<noteq> [] \<and> re (last tr) \<and> \<not> (\<exists>e\<in>set (butlast tr). mon e)"
proof -
  from assms have "tr \<in> checks n mx P
      (\<lambda>tr. tr \<noteq> [] \<and> re (last tr) \<and> \<not> (\<exists>e\<in>set (butlast tr). mon e))"
    by (simp add: check_corr_violation_def)
  from checks_sound[OF this] show ?thesis by simp
qed


subsection \<open> Classifying the state a trace reaches \<close>

text \<open>
  @{text state_kind} follows a trace of the model, spending at most \<open>mx\<close>
  internal steps between visible events, and reports how the run ends: a
  finished run, a deadlock, a divergence (the internal budget is exhausted), or
  a state that can still perform events.  The web interface uses it to label the
  leaves of the event tree it stores, so a leaf says whether the run terminated,
  deadlocked or diverged, as the hand-written explorer did.
\<close>

datatype skind = SContinues | STerminated | SDeadlocked | SDivergent

text \<open> The run is followed with an explicit fuel, so that the definition is
  structurally recursive and needs no termination proof: one visible event may
  be preceded by at most \<open>mx\<close> internal steps, hence
  \<open>(length tr + 1) * (mx + 1)\<close> steps always suffice. \<close>

fun follow_fuel :: "nat \<Rightarrow> nat \<Rightarrow> nat \<Rightarrow> ('e, 's) itree \<Rightarrow> 'e list \<Rightarrow> ('e, 's) itree" where
  "follow_fuel 0 mx t P tr = P"
| "follow_fuel (Suc f) mx (Suc t) (Sil P) tr = follow_fuel f mx t P tr"
| "follow_fuel (Suc f) mx 0 (Sil P) tr = Sil P"
| "follow_fuel (Suc f) mx t (Ret x) tr = Ret x"
| "follow_fuel (Suc f) mx t (Vis F) [] = Vis F"
| "follow_fuel (Suc f) mx t (Vis F) (e # tr) =
     (if e \<in> pdom F then follow_fuel f mx mx (F e) tr else Vis F)"

fun stop_kind :: "nat \<Rightarrow> ('e, 's) itree \<Rightarrow> skind" where
  "stop_kind t (Ret x) = STerminated"
| "stop_kind 0 (Sil P) = SDivergent"
| "stop_kind (Suc t) (Sil P) = stop_kind t P"
| "stop_kind t (Vis F) = (if pdom F = {} then SDeadlocked else SContinues)"

text \<open> The code generator represents \<open>nat\<close> as an opaque type, so the
  pattern equations above cannot be used directly; the following arithmetic
  equations are what is extracted. \<close>

lemma follow_fuel_code [code]:
  "follow_fuel f mx t P tr =
     (if f = 0 then P
      else case P of
             Sil Q \<Rightarrow> (if t = 0 then Sil Q else follow_fuel (f - 1) mx (t - 1) Q tr)
           | Ret x \<Rightarrow> Ret x
           | Vis F \<Rightarrow> (case tr of
                           [] \<Rightarrow> Vis F
                         | e # tr' \<Rightarrow> (if e \<in> pdom F
                                          then follow_fuel (f - 1) mx mx (F e) tr'
                                          else Vis F)))"
  by (cases f; cases P; cases t) (auto split: itree.splits list.splits)

lemma stop_kind_code [code]:
  "stop_kind t P =
     (case P of
        Ret x \<Rightarrow> STerminated
      | Sil Q \<Rightarrow> (if t = 0 then SDivergent else stop_kind (t - 1) Q)
      | Vis F \<Rightarrow> (if pdom F = {} then SDeadlocked else SContinues))"
  by (cases P; cases t) auto

declare follow_fuel.simps [code del]
declare stop_kind.simps [code del]

definition state_kind :: "nat \<Rightarrow> ('e, 's) itree \<Rightarrow> 'e list \<Rightarrow> skind" where
  "state_kind mx P tr = stop_kind mx (follow_fuel ((length tr + 1) * (mx + 1)) mx mx P tr)"

text \<open> The classification is the one of the hand-written explorer: a state
  whose domain is empty is a deadlock, an exhausted internal budget is a
  divergence, a finished run is termination, and anything else can continue. \<close>

lemma state_kind_Terminated:
  "state_kind mx (Ret x) tr = STerminated"
  by (cases "(length tr + 1) * (mx + 1)" rule: nat.exhaust) (simp_all add: state_kind_def)

lemma state_kind_Deadlocked:
  "pdom F = {} \<Longrightarrow> state_kind mx (Vis F) [] = SDeadlocked"
  by (cases "(length ([] :: 'e list) + 1) * (mx + 1)" rule: nat.exhaust)
     (simp_all add: state_kind_def)

lemma state_kind_Divergent:
  "state_kind 0 (Sil P) [] = SDivergent"
  by (simp add: state_kind_def)

subsection \<open> Sound exploration driver \<close>

text \<open> A generic driver for the Isabelle-extracted search.  It is compiled
  together with the exported model and the exported @{text explore} / @{text
  feasible} / @{text reaches} / @{text checks} functions.

  The driver needs \<open>Eq\<close> and \<open>Show\<close> instances for the event type of the model.
  The code generator emits them only when the exported definitions actually
  depend on them: in particular the \<open>Eq\<close> instance for a channel type is
  generated only if the model compares channels somewhere.  Should a model not
  do so, add a semantically neutral comparison to its definition (this is a
  known conservativity of the generator, not a soundness restriction). \<close>

generate_file \<open>code/simulate/Sound.hs\<close> = \<open>
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE FlexibleContexts #-}
module Sound (runSound) where
import Interaction_Trees (Itree(..), pdom, pfun_app)
import Prelude
import qualified Prelude
import Arith (nat_of_integer)
import qualified Set
import Sec_Animation (explore, budget_hit, check_leak, check_terminate, check_authenticity)
import System.Environment (getArgs)
import System.IO (hSetBuffering, stdin, stdout, BufferMode(NoBuffering, LineBuffering))
import System.IO.Error (tryIOError)

-- | Elements of a finite set, in the order in which the extracted search built it.
setToList :: forall a. Set.Set a -> [a]
setToList (Set.Set xs) = xs
setToList (Set.Coset _) = []

-- | The bounds used when the user just presses Return.
defaultBounds :: (Prelude.Integer, Prelude.Integer)
defaultBounds = (3, 3)

parseNat :: Prelude.String -> Prelude.Maybe Prelude.Integer
parseNat s = case Prelude.reads s of
  [(n, r)] | Prelude.all (== ' ') r -> Prelude.Just n
  _ -> Prelude.Nothing

-- | Ask for one bound, using the default on an empty answer or on end of input.
promptNat :: Prelude.String -> Prelude.Integer -> Prelude.IO Prelude.Integer
promptNat label def = do
  Prelude.putStr (label ++ " [" ++ Prelude.show def ++ "]: ")
  r <- tryIOError Prelude.getLine
  case r of
    Prelude.Left _ -> do
      Prelude.putStrLn ""
      return def
    Prelude.Right l -> case parseNat l of
      Prelude.Just v -> return v
      Prelude.Nothing -> return def

-- | Ask for the visible-event bound n and the internal-step bound mx.
askBounds :: Prelude.IO (Prelude.Integer, Prelude.Integer)
askBounds = do
  n <- promptNat "Visible-event bound n (bound on the number of visible events or trace length)" (Prelude.fst defaultBounds)
  mx <- promptNat "Internal-step bound mx (bound on internal steps between visible events)" (Prelude.snd defaultBounds)
  return (n, mx)

-- | Print all explored traces.
showTraces :: (Prelude.Show e) => [e] -> Prelude.IO ()
showTraces ts = do
  Prelude.putStrLn ("*** " ++ Prelude.show (Prelude.length ts) ++ " traces within the bounds ***")
  Prelude.mapM_ (\tr -> Prelude.putStrLn ("  " ++ Prelude.show tr)) ts

-- | Report the counterexamples returned by a check; empty means none were found.
report :: (Prelude.Show e) => Prelude.String -> [e] -> Prelude.IO ()
report label ts = case ts of
  [] -> Prelude.putStrLn ("No " ++ label ++ " counterexample within the bounds.")
  _ -> do
    Prelude.putStrLn ("*** " ++ Prelude.show (Prelude.length ts) ++ " " ++ label ++ " counterexample(s) found ***")
    Prelude.mapM_ (\tr -> Prelude.putStrLn ("  " ++ Prelude.show tr)) ts

-- | Print the trace followed so far.
reportTrace :: (Prelude.Show e) => [e] -> Prelude.IO ()
reportTrace tr = Prelude.putStrLn ("Trace: " ++ Prelude.show tr)

-- | Print the enabled events of the current state, numbered.
showEvents :: (Prelude.Show e) => [e] -> Prelude.IO ()
showEvents es =
  Prelude.mapM_ (\(i, e) -> Prelude.putStrLn ("  (" ++ Prelude.show i ++ ") " ++ Prelude.show e))
    (Prelude.zip [(1 :: Prelude.Int) ..] es)

-- | Step through the animation manually: at every visible state the enabled
-- events are listed and the user chooses one by its number, and "q" stops.
-- The internal-step bound is the fuel spent between two visible events, and
-- the visible-event bound caps the length of the trace.
manualExplore :: forall e s. (Eq e, Prelude.Show e) =>
  Prelude.Integer -> Prelude.Integer -> [e] -> Itree e s -> Prelude.IO ()
manualExplore n mx = go mx
  where
    go :: Prelude.Integer -> [e] -> Itree e s -> Prelude.IO ()
    go fuel tr p
      | Prelude.toInteger (Prelude.length tr) >= n = done "Visible-event bound reached." tr
      | otherwise = case p of
          Ret _ -> done "Terminated." tr
          Sil q -> if fuel <= 0
            then done "Divergent (internal-step budget exhausted)." tr
            else go (fuel - 1) tr q
          Vis f -> do
            let es = setToList (pdom f)
            if Prelude.null es
              then done "Deadlocked." tr
              else do
                Prelude.putStrLn "Events:"
                showEvents es
                Prelude.putStr ("[Choose: 1-" ++ Prelude.show (Prelude.length es) ++ ", q to quit]: ")
                r <- tryIOError Prelude.getLine
                case r of
                  Prelude.Left _ -> done "" tr
                  Prelude.Right s
                    | s `Prelude.elem` ["q", "Q"] -> done "Manual exploration terminated." tr
                    | otherwise -> case parseNat s of
                        Prelude.Just v
                          | v >= 1 && v <= Prelude.toInteger (Prelude.length es) -> do
                              let e = es Prelude.!! (Prelude.fromInteger v - 1)
                              Prelude.putStrLn ("Chosen: " ++ Prelude.show e)
                              go mx (tr Prelude.++ [e]) (pfun_app f e)
                        _ -> do
                          Prelude.putStrLn "No parse"
                          go fuel tr p
    done :: Prelude.String -> [e] -> Prelude.IO ()
    done msg tr = do
      Prelude.putStrLn msg
      reportTrace tr

-- | Run the sound bounded exploration and checking of an ITree.
-- The bounds are the first two command-line arguments if given, otherwise the
-- user is prompted for n and mx; the check is then chosen interactively.
runSound p = do
  hSetBuffering stdout NoBuffering
  hSetBuffering stdin LineBuffering
  Prelude.putStrLn "Sound bounded exploration / checking (search extracted from Isabelle/HOL)"
  args <- getArgs
  (n, mx) <- case args of
    (a : b : _) -> case (parseNat a, parseNat b) of
      (Prelude.Just n', Prelude.Just m') -> return (n', m')
      _ -> askBounds
    _ -> askBounds
  let nn = nat_of_integer n
      mm = nat_of_integer mx
  if budget_hit nn mm mm p
    then Prelude.putStrLn ("WARNING: the internal-step budget (mx = " ++ Prelude.show mx
           ++ ") was exhausted and the search was cut short, so this result is not exhaustive"
           ++ " within n = " ++ Prelude.show n
           ++ ".  Re-run with a larger mx for a complete answer.")
    else Prelude.return ()
  Prelude.putStrLn "Which check? (5 steps through the animation manually)"
  Prelude.putStrLn "  1) enumerate all traces within the bounds"
  Prelude.putStrLn "  2) secrecy: traces containing a Leak event"
  Prelude.putStrLn "  3) completion: traces containing a Terminate event"
  Prelude.putStrLn "  4) authenticity: a completed run whose counterpart never started it"
  Prelude.putStrLn "  5) manual exploration: choose one event at a time"
  Prelude.putStr "Check [1]: "
  c <- tryIOError Prelude.getLine
  case c of
    Prelude.Left _ -> showTraces (setToList (explore nn mm mm p))
    Prelude.Right l -> case l of
      "2" -> report "Leak" (setToList (check_leak nn mm p))
      "3" -> report "Terminate" (setToList (check_terminate nn mm p))
      "4" -> report "authenticity" (setToList (check_authenticity nn mm p))
      "5" -> manualExplore n mx [] p
      _ -> showTraces (setToList (explore nn mm mm p))
\<close>

ML \<open> 
structure ITree_Simulator =
struct

structure ISim_Path = Theory_Data
  (type T = Path.T option
   val empty = NONE
   val extend = I
   val merge = fn (_, y) => y);

fun simulator_setup thy = 
  let open Isabelle_System; val tmp = Path.expand (create_tmp_path "itree-simulate" "")
  in case (ISim_Path.get thy) of NONE => () | SOME oldtmp => rm_tree oldtmp;
    make_directory tmp; (tmp, ISim_Path.put (SOME tmp) thy)
  end

(* GHC resolution.  The distribution default for @{verbatim ISABELLE_GHC} may
   point at a compiler that is not installed, so check it first and otherwise
   fall back to ghcup and then to @{verbatim ghc} on the PATH. *)
fun ghc_exe () =
  let
    val isa = getenv "ISABELLE_GHC"
    val home = getenv "HOME"
    val ghcup = home ^ "/.ghcup/bin/ghc"
  in
    if isa <> "" andalso File.exists (Path.explode isa) then isa
    else if home <> "" andalso File.exists (Path.explode ghcup) then ghcup
    else if #2 (Isabelle_System.bash_output "command -v ghc") = 0 then "ghc"
    else error ("GHC not found. Set ISABELLE_GHC in " ^ getenv "ISABELLE_HOME_USER" ^
      "/etc/settings, or put ghc on the PATH.")
  end

fun sim_files_cp_bin bin tmp = 
  let val ghc = ghc_exe ()
  in
  "(fn path => let open Isabelle_System; val path' = Path.append path (Path.make [\"code\", \"simulate\"])" ^
  " in writeln \"Compiling animation...\"; bash (\"cd \" ^ Path.implode path' ^ \"; " ^ ghc ^ " " ^ bin ^ " >> /dev/null\") ; copy_dir path' (Path.explode \"" ^ tmp ^ "\") end)"
  end

fun sim_files_cp tmp = sim_files_cp_bin "Simulation" tmp

open Named_Target

fun firstLower s =
  case String.explode s of [] => "" | c :: cs => String.implode (Char.toLower c :: cs);

fun simulation_file model thy =
  "module Main where \n" ^
  "import Simulate; \n" ^
  "import " ^ thy ^ "; \n" ^
  "main = simulate " ^ firstLower model

fun prep_simulation model thy ctx =
  let open Generated_Files; 
      val (tmp, thy') = simulator_setup (Local_Theory.exit_global ctx);
      val ctx' = Named_Target.theory_init thy'
      val _ = ghc_exe ()
  in
  generate_file (Path.binding0 (Path.make ["code", "simulate", "Simulation.hs"]), (Input.string (simulation_file model thy))) ctx' |>
  (fn ctx' => 
    let val _ = compile_generated_files 
                 ctx'
                 [([], (Local_Theory.exit_global ctx')), ([Path.binding0 (Path.make ["code", "simulate", "Simulate.hs"])], @{theory})] 
                 [] [([Path.binding0 (Path.make ["code", "simulate", "Simulation"])], SOME true)]
                 (Path.binding0 (Path.make []))
                 (Input.string (sim_files_cp (Path.implode tmp)))
    in ctx' end)


(*  (fn ctx => let val _ = export_generated_files ctx [([], Local_Theory.exit_global ctx), ([], @{theory})] in ctx end) *)
  end

fun run_simulation thy =
  case ISim_Path.get thy of
    NONE => error "No animation" |
    SOME f => writeln (Active.run_system_shell_command (SOME (Path.implode f)) ("./simulate/Simulation") "Start animation")

fun simulate model thy =
  let val ctx = Named_Target.theory_init thy
      val ctx' =
        (Code_Target.export_code true [Code.read_const (Local_Theory.exit_global ctx) model] [((("Haskell", ""), SOME ({physical = false}, (Path.explode "simulate", Position.none))), (Token.explode (Thy_Header.get_keywords' @{context}) Position.none "string_classes"))] ctx)
        |> prep_simulation model (Context.theory_name {long = false} thy)
  in run_simulation (Local_Theory.exit_global ctx'); (Local_Theory.exit_global ctx')
  end 

fun sound_main_file model thy =
  "module Main where \n" ^
  "import Sound; \n" ^
  "import " ^ thy ^ "; \n" ^
  "main = runSound " ^ firstLower model

fun prep_sound model thy ctx =
  let open Generated_Files;
      val (tmp, thy') = simulator_setup (Local_Theory.exit_global ctx);
      val ctx' = Named_Target.theory_init thy'
      val _ = ghc_exe ()
  in
  generate_file (Path.binding0 (Path.make ["code", "simulate", "SoundMain.hs"]), (Input.string (sound_main_file model thy))) ctx' |>
  (fn ctx' =>
    let val _ = compile_generated_files
                 ctx'
                 [([], (Local_Theory.exit_global ctx')), ([Path.binding0 (Path.make ["code", "simulate", "Sound.hs"])], @{theory})]
                 [] [([Path.binding0 (Path.make ["code", "simulate", "SoundMain"])], SOME true)]
                 (Path.binding0 (Path.make []))
                 (Input.string (sim_files_cp_bin "SoundMain" (Path.implode tmp)))
    in ctx' end)

  end

fun run_sound thy =
  case ISim_Path.get thy of
    NONE => error "No sound exploration" |
    SOME f => writeln (Active.run_system_shell_command (SOME (Path.implode f)) ("./simulate/SoundMain") "Start sound exploration")

(* Export the model together with the Isabelle-defined search, so that the
   exploration performed at run time is the one proved sound and complete. *)
fun sound_simulate model thy =
  let val ctx = Named_Target.theory_init thy
      val thy0 = Local_Theory.exit_global ctx
      val cs = map (Code.read_const thy0)
        [model, "explore", "budget_hit", "feasible", "reaches", "checks", "check_leak",
         "check_leak_msg", "check_sig", "check_terminate", "check_corr",
         "check_corr_violation", "check_authenticity"]
      val ctx' =
        (Code_Target.export_code true cs [((("Haskell", ""), SOME ({physical = false}, (Path.explode "simulate", Position.none))), (Token.explode (Thy_Header.get_keywords' @{context}) Position.none "string_classes"))] ctx)
        |> prep_sound model (Context.theory_name {long = false} thy)
  in run_sound (Local_Theory.exit_global ctx'); (Local_Theory.exit_global ctx')
  end 

end;
\<close>

ML \<open>
  Outer_Syntax.command @{command_keyword animate_sec} "animate an ITree"
  (Parse.name >> (fn model => Toplevel.theory (ITree_Simulator.simulate model)))
\<close>

ML \<open>
  Outer_Syntax.command @{command_keyword animate_sec_sound} "soundly explore an ITree"
  (Parse.name >> (fn model => Toplevel.theory (ITree_Simulator.sound_simulate model)))
\<close>

end
